// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ChangeTheaterTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void changeTheater() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(1920, 999));
    driver.findElement(By.linkText("Театры")).click();
    driver.findElement(By.linkText("Большой театр")).click();
    driver.findElement(By.linkText("Изменить театр")).click();
    driver.findElement(By.id("name")).click();
    driver.findElement(By.id("name")).sendKeys("Большой театр123");
    driver.findElement(By.id("phone")).click();
    driver.findElement(By.id("phone")).click();
    driver.findElement(By.id("phone")).sendKeys("88005553535");
    driver.findElement(By.id("address")).click();
    driver.findElement(By.id("address")).sendKeys("Театральная пл., 2");
    driver.findElement(By.cssSelector("button")).click();
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(2)")).getText(), is("Большой театр123"));
    assertThat(driver.findElement(By.cssSelector("td li:nth-child(3)")).getText(), is("Театральная пл., 2"));
    driver.findElement(By.linkText("Изменить театр")).click();
    driver.findElement(By.id("name")).click();
    driver.findElement(By.id("name")).sendKeys("Большой театр");
    driver.findElement(By.cssSelector("form li:nth-child(2)")).click();
    driver.findElement(By.cssSelector("button")).click();
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(2)")).getText(), is("Большой театр"));
    assertThat(driver.findElement(By.cssSelector("td li:nth-child(2)")).getText(), is("www.bolshoi.ru"));
  }
}
