// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class NewMemberTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void newMember() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(1920, 999));
    driver.findElement(By.linkText("Участники")).click();
    driver.findElement(By.linkText("Спектакли")).click();
    driver.findElement(By.linkText("Весы")).click();
    driver.findElement(By.linkText("Изменить спектакль")).click();
    driver.findElement(By.cssSelector("button:nth-child(8)")).click();
    driver.findElement(By.id("name")).click();
    driver.findElement(By.id("name")).sendKeys("Тест");
    driver.findElement(By.id("description")).click();
    driver.findElement(By.id("description")).sendKeys("тест");
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.cssSelector(".logo")).click();
    driver.findElement(By.cssSelector("ul")).click();
    driver.findElement(By.linkText("Участники")).click();
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(9) > td:nth-child(1)")).getText(), is("Тест"));
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(9) > td:nth-child(2)")).getText(), is("тест"));
    driver.findElement(By.cssSelector("tr:nth-child(9) button")).click();
    driver.findElement(By.cssSelector("body")).click();
  }
}
