// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class NewPerformanceTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void newPerformance() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(1920, 999));
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.linkText("Добавить спектакль")).click();
    driver.findElement(By.id("name")).click();
    driver.findElement(By.id("name")).sendKeys("Тест");
    driver.findElement(By.cssSelector("form li:nth-child(2)")).click();
    driver.findElement(By.id("duration")).click();
    driver.findElement(By.id("duration")).sendKeys("01:30");
    driver.findElement(By.id("start")).click();
    driver.findElement(By.id("start")).sendKeys("2021-05-01");
    driver.findElement(By.id("finish")).click();
    driver.findElement(By.id("finish")).sendKeys("2021-05-31");
    driver.findElement(By.id("description")).click();
    driver.findElement(By.id("description")).sendKeys("Тест");
    driver.findElement(By.cssSelector("button")).click();
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(4) > td:nth-child(1)")).getText(), is("Тест"));
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(4) > td:nth-child(2)")).getText(), is("2021-05-01 - 2021-05-31"));
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(4) > td:nth-child(3)")).getText(), is("Большой театр"));
    driver.findElement(By.linkText("Тест")).click();
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(2)")).getText(), is("Тест"));
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.cssSelector("body")).click();
  }
}
